### ISSUE TITLE
PayHereOnDismissedHandler issue (Bottomsheet not dismissed)

### ISSUE THREAD

**Issue by KavinduDissanayake** [PayHereLK/payhere-mobilesdk-flutter#16]
with flutter getx , most of the time payment bottom sheet is not demised, at least not called the PayHereOnDismissedHandler on Dismissed) this call back > Major bug

![Screenshot 2023-07-30 185308](https://github.com/PayHereLK/payhere-mobilesdk-flutter/assets/51842810/284ef08e-b503-4d8d-97f1-6946415f008c)

**Comment by KavinduDissanayake** [comment]
Log Details 

`I/FLTFireMsgService(15191): FlutterFirebaseMessagingBackgroundService started!
D/PayHereBaseActivity(15191): Session timer enabled
D/PayHereBaseActivity(15191): Session timer Restarted
W/eraautocare.de(15191): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
W/eraautocare.de(15191): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
W/eraautocare.de(15191): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (unsupported,core-platform-api, reflection, allowed)
W/eraautocare.de(15191): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (unsupported,core-platform-api, reflection, allowed)
W/eraautocare.de(15191): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (unsupported,core-platform-api, reflection, allowed)
D/CompatibilityChangeReporter(15191): Compat change id reported: 171228096; UID 10145; state: ENABLED
W/Glide   (15191): Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
D/PayHereBaseActivity(15191): Session timer Restarted
D/PaymentMethodFragment(15191): Init Payment method success
D/EGL_emulation(15191): app_time_stats: avg=12.72ms min=2.64ms max=115.21ms count=32
W/Glide   (15191): Load failed for https://sandbox.payhere.lk/pay/resources/images/pm/2x/no_image.png with size [96x96]
W/Glide   (15191): class com.bumptech.glide.load.engine.GlideException: Failed to load resource
W/Glide   (15191): There was 1 root cause:
W/Glide   (15191): com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: 404)
W/Glide   (15191):  call GlideException#logRootCauses(String) for more detail
W/Glide   (15191):   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
W/Glide   (15191): There was 1 root cause:
W/Glide   (15191): com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: 404)
W/Glide   (15191):  call GlideException#logRootCauses(String) for more detail
W/Glide   (15191):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
W/Glide   (15191): There was 1 root cause:
W/Glide   (15191): com.bumptech.glide.load.HttpException(Failed to connect or obtain data, status code: 404)
W/Glide   (15191):  call GlideException#logRootCauses(String) for more detail
W/Glide   (15191):       Cause (1 of 1): class com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: 404
I/Glide   (15191): Root cause (1 of 1)
I/Glide   (15191): com.bumptech.glide.load.HttpException: Failed to connect or obtain data, status code: 404
I/Glide   (15191): 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:98)
I/Glide   (15191): 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:58)
I/Glide   (15191): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (15191): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
I/Glide   (15191): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
I/Glide   (15191): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
I/Glide   (15191): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
I/Glide   (15191): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
I/Glide   (15191): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/Glide   (15191): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/Glide   (15191): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:413)
I/Glide   (15191): 	at java.lang.Thread.run(Thread.java:920)
I/Glide   (15191): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:372)
I/Glide   (15191): Caused by: java.io.FileNotFoundException: https://sandbox.payhere.lk/pay/resources/images/pm/2x/no_image.png
I/Glide   (15191): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
I/Glide   (15191): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
I/Glide   (15191): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
I/Glide   (15191): 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:95)
I/Glide   (15191): 	... 12 more
D/PayHereBaseActivity(15191): Session timer Restarted
D/PHMainActivity(15191): Bottom Sheet state : 2
D/EGL_emulation(15191): app_time_stats: avg=675.51ms min=48.10ms max=1302.91ms count=2
D/PHMainActivity(15191): Bottom Sheet state : 4
`
