### ISSUE TITLE
Application crash when click the payment option

### ISSUE THREAD

**Issue by nishalsehan** [PayHereLK/payhere-mobilesdk-flutter#4]
I wasted 2 days finding a solution. But still, I can't find it. 

This is the log

D/PHMainActivity( 8951): Bottom Sheet state : 3
I/WebViewFactory( 8951): Loading com.android.webview version 39 (6695563-x86) (code 300007)
I/LibraryLoader( 8951): Time to load native libraries: 1 ms (timestamps 3933-3934)
I/LibraryLoader( 8951): Expected native library version number "",actual native library version number ""
V/WebViewChromiumFactoryProvider( 8951): Binding Chromium to main looper Looper (main, tid 1) {2c8862f9}
I/LibraryLoader( 8951): Expected native library version number "",actual native library version number ""
I/chromium( 8951): [INFO:library_loader_hooks.cc(104)] Chromium logging enabled: level = 0, default verbosity = 0
I/BrowserStartupController( 8951): Initializing chromium process, singleProcess=true
W/art     ( 8951): Attempt to remove local handle scope entry from IRT, ignoring
W/chromium( 8951): [WARNING:resource_bundle.cc(304)] locale_file_path.empty()
I/chromium( 8951): [INFO:aw_browser_main_parts.cc(65)] Load from apk succesful, fd=80 off=46184 len=3037
I/chromium( 8951): [INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:81 off:229484 len:1089587
E/BluetoothAdapter( 8951): Bluetooth binder is null
D/EGL_emulation( 8951): eglCreateContext: 0x94728e20: maj 2 min 0 rcv 2
D/EGL_emulation( 8951): eglMakeCurrent: 0x94728e20: ver 2 0 (tinfo 0x9fc5c330)
W/chromium( 8951): [WARNING:data_reduction_proxy_settings.cc(331)] SPDY proxy OFF at startup
W/ResourceType( 8951): No known package when getting value for resource number 0x02040003
D/AndroidRuntime( 8951): Shutting down VM
E/AndroidRuntime( 8951): FATAL EXCEPTION: main
E/AndroidRuntime( 8951): android.view.InflateException: Binary XML file line #7: Error inflating class lk.payhere.androidsdk.util.ObservableWebView
E/AndroidRuntime( 8951): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
E/AndroidRuntime( 8951): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
E/AndroidRuntime( 8951): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime( 8951): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime( 8951): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime( 8951): 	at lk.payhere.androidsdk.fragment.PaymentDetailFragment.onCreateView(PaymentDetailFragment.java:101)
E/AndroidRuntime( 8951): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
E/AndroidRuntime( 8951): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
E/AndroidRuntime( 8951): 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
E/AndroidRuntime( 8951): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
E/AndroidRuntime( 8951): 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
E/AndroidRuntime( 8951): 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
E/AndroidRuntime( 8951): 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
E/AndroidRuntime( 8951): 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
E/AndroidRuntime( 8951): 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
E/AndroidRuntime( 8951): 	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
E/AndroidRuntime( 8951): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 8951): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 8951): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 8951): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 8951): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8951): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 8951): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 8951): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 8951): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 8951): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime( 8951): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime( 8951): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
E/AndroidRuntime( 8951): 	... 23 more
E/AndroidRuntime( 8951): Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
E/AndroidRuntime( 8951): 	at android.content.res.Resources.getText(Resources.java:299)
E/AndroidRuntime( 8951): 	at android.content.res.Resources.getString(Resources.java:385)
E/AndroidRuntime( 8951): 	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
E/AndroidRuntime( 8951): 	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
E/AndroidRuntime( 8951): 	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
E/AndroidRuntime( 8951): 	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
E/AndroidRuntime( 8951): 	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
E/AndroidRuntime( 8951): 	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
E/AndroidRuntime( 8951): 	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:311)
E/AndroidRuntime( 8951): 	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
E/AndroidRuntime( 8951): 	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:263)
E/AndroidRuntime( 8951): 	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
E/AndroidRuntime( 8951): 	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
E/AndroidRuntime( 8951): 	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
E/AndroidRuntime( 8951): 	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
E/AndroidRuntime( 8951): 	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:260)
E/AndroidRuntime( 8951): 	at android.webkit.WebView.<init>(WebView.java:554)
E/AndroidRuntime( 8951): 	at android.webkit.WebView.<init>(WebView.java:489)
E/AndroidRuntime( 8951): 	at android.webkit.WebView.<init>(WebView.java:472)
E/AndroidRuntime( 8951): 	at android.webkit.WebView.<init>(WebView.java:459)
E/AndroidRuntime( 8951): 	at lk.payhere.androidsdk.util.Observable

**Comment by PayHereDevs** [comment]
Dear @nishalsehan,

We apologize for the delayed response. This could be an issue related to running the application on the Simulator, or if your physical Android device has low memory. Additionally, you can check whether you have upgraded to the Android X libraries as documented [here](https://flutter.dev/docs/development/androidx-migration).

Further, by "Application Crash" we assume the entire app crashes and not just the PayHere Bottom Sheet being dismissed automatically. If you originally meant that the Bottom Sheet closes automatically, please let us know and we will instruct you with the next steps.
